export const timezones = [
  "(UTC-12:00) International Date Line West",
  "(UTC-11:00) Coordinated Universal Time-11",
  "(UTC-10:00) Hawaii",
  "(UTC-09:00) Alaska",
  "(UTC-08:00) Pacific Time (US & Canada)",
  "(UTC-07:00) Mountain Time (US & Canada)",
  "(UTC-06:00) Central Time (US & Canada)",
  "(UTC-05:00) Eastern Time (US & Canada)",
  "(UTC-04:00) Atlantic Time (Canada)",
  "(UTC-03:30) Newfoundland",
  "(UTC-03:00) Brasilia, Buenos Aires",
  "(UTC-02:00) Mid-Atlantic",
  "(UTC-01:00) Azores, Cape Verde",
  "(UTC+00:00) London, Dublin, Lisbon, Accra, Dakar, Abidjan",
  "(UTC+01:00) Paris, Berlin, Rome, Lagos, Algiers, Casablanca, Tunis",
  "(UTC+02:00) Cairo, Johannesburg, Harare, Cape Town, Tripoli, Khartoum",
  "(UTC+03:00) Nairobi, Addis Ababa, Dar es Salaam, Mogadishu, Moscow, Riyadh",
  "(UTC+03:30) Tehran",
  "(UTC+04:00) Dubai, Mauritius, Seychelles, Baku, Samara",
  "(UTC+04:30) Kabul",
  "(UTC+05:00) Karachi, Tashkent",
  "(UTC+05:30) India Standard Time",
  "(UTC+05:45) Kathmandu",
  "(UTC+06:00) Dhaka, Almaty",
  "(UTC+06:30) Yangon",
  "(UTC+07:00) Bangkok, Hanoi, Jakarta",
  "(UTC+08:00) Beijing, Singapore, Perth",
  "(UTC+08:45) Eucla",
  "(UTC+09:00) Tokyo, Seoul, Osaka",
  "(UTC+09:30) Adelaide, Darwin",
  "(UTC+10:00) Sydney, Melbourne, Brisbane",
  "(UTC+10:30) Lord Howe Island",
  "(UTC+11:00) Solomon Islands, New Caledonia",
  "(UTC+12:00) Auckland, Fiji, Kamchatka",
  "(UTC+12:45) Chatham Islands",
  "(UTC+13:00) Samoa, Tonga",
  "(UTC+14:00) Kiritimati Island",
];
