import type { Metadata } from "next";
import { DynamicFooter } from "../../_components/footer/dynamic-footer";
import type { Contributor } from "./_components/contributor-card";
import { ContributorsList } from "./_components/contributors-list";

export const metadata: Metadata = {
  title: "Zedu Macaw Contributors",
  description:
    "Meet the contributors who helped build the Zedu Macaw release - the designers, engineers, and community members shaping modern learning.",
  keywords: [
    "Zedu contributors",
    "Zedu Macaw",
    "open source contributors",
    "learning platform contributors",
    "Zedu community",
  ],
  openGraph: {
    title: "Zedu Macaw Contributors",
    description:
      "A thank you to everyone who contributed to the Zedu Macaw release.",
    url: "/contributors/macaw",
    siteName: "Zedu",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Zedu Macaw Contributors",
    description:
      "A thank you to everyone who contributed to the Zedu Macaw release.",
  },
  alternates: {
    canonical: "/contributors/macaw",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const contributors: Contributor[] = [
  {
    id: "1",
    name: "Chisom Aniekwensi",
    username: "ChisomAniekwensi",
    workspaceEmail: "sommaniekwensi@gmail.com",
    gitHubEmail: "sommaniekwensi@gmail.com",
    role: "Team Lead",
    hobbies: [],
  },
  {
    id: "2",
    name: "Olaleye Obidiya",
    username: "onyx_oceanview",
    workspaceEmail: "olaleyeobidiya@gmail.com",
    gitHubEmail: "olaleyeobidiya@gmail.com",
    role: "technical lead",
    hobbies: ["swimming", "football", "chess", "traveling"],
  },
  {
    id: "3",
    name: "Okoro Theresa Chioma",
    username: "okorotheresa149-spec",
    workspaceEmail: "Okorotessy149@gmail.com",
    gitHubEmail: "okorotessy149@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "4",
    name: "Azeezah Fasasi",
    username: "azeezah fasasi",
    workspaceEmail: "fas4azeezah@gmail.com",
    gitHubEmail: "fas4azeezah@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "5",
    name: "Oluwasegun Ikoya",
    username: "OluwasegunIkoya",
    workspaceEmail: "oluwasegunikoya@gmail.com",
    gitHubEmail: "emmanuelikoya99@gmail.com",
    role: "member",
    hobbies: ["Djing", "Music Production", "Music Mixing", "Jogging"],
  },
  {
    id: "6",
    name: "Muhammad Abdullahi Makarfi",
    username: "Muhammad Abdullahi Makarfi",
    workspaceEmail: "ma9008180@gmail.com",
    gitHubEmail: "ma9008180@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "7",
    name: "Ojeaburu wisdom Omogafen",
    username: "Wisdom Ojeaburu",
    workspaceEmail: "wisojeaburu@gmail.com",
    gitHubEmail: "peroprimus1234@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "8",
    name: "Fredrick Vivian Chizoba",
    username: "Vivian Chizoba Fredrick",
    workspaceEmail: "fredrickvivian057@gmail.com",
    gitHubEmail: "fredrickvivian057@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "9",
    name: "Lasisi Oluwatimilehin Joshua",
    username: "Lasisi Oluwatimilehin Joshua",
    workspaceEmail: "lasisitimilehin9@gmail.com",
    gitHubEmail: "lasisitimilehin9@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "10",
    name: "Akinwande Joseph Obiti",
    username: "akinwandeobiti",
    workspaceEmail: "akinwandeobiti@gmail.com",
    gitHubEmail: "obitiakinwandeno1@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "11",
    name: "Afolarin Segun Sunday",
    username: "Mash",
    workspaceEmail: "afolarinsegun@gmail.com",
    gitHubEmail: "afolarinsegun@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "12",
    name: "Abonyi Izuvhukwu",
    username: "Izuchukwu",
    workspaceEmail: "abonyiizuchukwu@gmail.com",
    gitHubEmail: "abonyiizuchukwu@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "13",
    name: "Ngozi Orji",
    username: "Blizz",
    workspaceEmail: "ngoziorji75@gmail.com",
    gitHubEmail: "ngoziorji75@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "14",
    name: "Tochukwu Obinna",
    username: "Tunchi-0805",
    workspaceEmail: "tunchiprova@gmail.com",
    gitHubEmail: "Sijoshleon@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "15",
    name: "Olatuja Victor Toluwanimi",
    username: "vance",
    workspaceEmail: "mrxxvector@gmail.com",
    gitHubEmail: "mrxxvector@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "16",
    name: "Michael Felix",
    username: "Michael Felix",
    workspaceEmail: "mikelphelix@gmail.com",
    gitHubEmail: "agboolaademichael@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "17",
    name: "Umeh chinonye Juliet",
    username: "Chinonye Umeh",
    workspaceEmail: "Chinonyejulz@gmail.com",
    gitHubEmail: "Chinonyejulz@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "18",
    name: "Grace Oyemade",
    username: "@graceoyemade",
    workspaceEmail: "graceopeoyemade@gmail.com",
    gitHubEmail: "graceopeoyemade@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "19",
    name: "King Jaleel",
    username: "Jaleel",
    workspaceEmail: "odetolababs@gmail.com",
    gitHubEmail: "sirfunsho",
    role: "member",
    hobbies: [],
  },
  {
    id: "20",
    name: "Muhammad Alameen Adamu",
    username: "Alameentoro",
    workspaceEmail: "muhammadtt97@gmail.com",
    gitHubEmail: "muhammadtt97@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "21",
    name: "Stephen Omachonu",
    username: "stephen omachonu",
    workspaceEmail: "stephomac89@gmail.com",
    gitHubEmail: "somachonu.2302393@stu.cu.edu.ng",
    role: "member",
    hobbies: [],
  },
  {
    id: "22",
    name: "Yusuf Muhammad Musa",
    username: "yusuufmm",
    workspaceEmail: "yusuf2000mm@gmail.com",
    gitHubEmail: "yusuf2000mm@gmail.com",
    role: "member",
    hobbies: ["Coding", "Gaming"],
  },
  {
    id: "23",
    name: "Ikemefuna Nwodo",
    username: "Ikemefuna nwodo",
    workspaceEmail: "Nwodofrank@gmail.com",
    gitHubEmail: "Nwodofrank@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "24",
    name: "daniel field",
    username: "danchofield1",
    workspaceEmail: "danchofield1@yahoo.com",
    gitHubEmail: "Fieldpresido1",
    role: "member",
    hobbies: [],
  },
  {
    id: "25",
    name: "Oyelami Sekinat Ebunoluwa",
    username: "GiftyHealthTech",
    workspaceEmail: "sekinatoyelami@gmail.com",
    gitHubEmail: "sekinatoyelami@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "26",
    name: "Priscilla Bertley",
    username: "bertley priscy",
    workspaceEmail: "bertleypriscy@gmail.com",
    gitHubEmail: "bertleypriscy@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "27",
    name: "Samson Ocran",
    username: "Samson Ocran",
    workspaceEmail: "samson.ocran@gmail.com",
    gitHubEmail: "samson.ocran@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "28",
    name: "Olapite Oluwadolapo",
    username: "Dolappy",
    workspaceEmail: "olapitedolapo@gmail.com",
    gitHubEmail: "olapitedolapo@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "29",
    name: "Joshua",
    username: "Jboy",
    workspaceEmail: "onitimilehin87@gmail.com",
    gitHubEmail: "onitimilehin87@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "30",
    name: "Mustapha Bashir",
    username: "@mustapha_bashir",
    workspaceEmail: "mustaphabashir348@gmail.com",
    gitHubEmail: "mustaphabashir348@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "31",
    name: "Abdulganiyu Abu",
    username: "ganiyu ganiyu_01a0ca1c",
    workspaceEmail: "Ganiyuabu2@gmail.com",
    gitHubEmail: "Ganiyuabu2@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "32",
    name: "Ciary Ben Alok",
    username: "ciaryben623",
    workspaceEmail: "ciaryben623@gmail.com",
    gitHubEmail: "ciaryben623@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "33",
    name: "Adetunji Abosede Esther",
    username: "Tema",
    workspaceEmail: "adetunjibose2018@gmail.com",
    gitHubEmail: "adetunjibose2018@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "34",
    name: "Ijeoma Egbeke",
    username: "Ijeoma Egbeke",
    workspaceEmail: "ijeomaegbeke@gmail.com",
    gitHubEmail: "ijeomaegbeke@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "35",
    name: "Muhammad Abdullahi Kutigi",
    username: "Muhammad_Kutigi",
    workspaceEmail: "muhammadkutigi90@gmail.com",
    gitHubEmail: "muhammadkutigi90@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "36",
    name: "Paul Momoh",
    username: "boootconverse",
    workspaceEmail: "boootconverse@gmail.com",
    gitHubEmail: "dumeccs@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "37",
    name: "Okoli Chidozie Kingsley",
    username: "Chidozie",
    workspaceEmail: "chidozie4god@gmail.com",
    gitHubEmail: "chidozie4god@gmail.com",
    role: "member",
    hobbies: ["gaming", "football", "volleyball"],
  },
  {
    id: "38",
    name: "Nwodo Destiny",
    username: "destiny nwodo",
    workspaceEmail: "dessynwodo@gmail.com",
    gitHubEmail: "dessynwodo@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "39",
    name: "Joel Nwaelugo",
    username: "joelnwaelugo",
    workspaceEmail: "joelnwaelugo@gmail.com",
    gitHubEmail: "joelnwaelugo@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "40",
    name: "Funsho Kamoru",
    username: "Funsho",
    workspaceEmail: "funshoamoru@gmail.com",
    gitHubEmail: "funshokamoru@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "41",
    name: "Chioma Esther Okpor",
    username: "Chioma Okpor",
    workspaceEmail: "estee.ojumah@gmail.com",
    gitHubEmail: "estee.ojumah@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "42",
    name: "Kenneth okonkwo",
    username: "Kenneth okonkwo",
    workspaceEmail: "kennethokonkwo73@gmail.com",
    gitHubEmail: "kennethokonkwo73@gmail.com",
    role: "member",
    hobbies: ["Football", "Music", "Travelling"],
  },
  {
    id: "43",
    name: "Chiamaka Favour Amaechi",
    username: "chifav",
    workspaceEmail: "chifav312@gmail.com",
    gitHubEmail: "chifav312@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "44",
    name: "Oluwakorede Serah Banfe",
    username: "Holuwahkorede",
    workspaceEmail: "holuwahkoredebanfe@gmail.com",
    gitHubEmail: "oluwakoredebanfe@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "45",
    name: "Oki Blessing",
    username: "blessingoki94",
    workspaceEmail: "blessingoki94@gmail.com",
    gitHubEmail: "blessingoki94@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "46",
    name: "ArnoldNyamongo",
    username: "ArnoldNyamongo",
    workspaceEmail: "arnoldnyams@gmail.com",
    gitHubEmail: "arnoldnyams@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "47",
    name: "Iniobong Ekpenyong",
    username: "iniobong ekpenyong",
    workspaceEmail: "iniobongmichaelekpenyong@gmail.com",
    gitHubEmail: "iniobongmichaelekpenyong@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "48",
    name: "Shittu Sammiat Ayomide",
    username: "Sammiat49",
    workspaceEmail: "sammiat49@gmail.com",
    gitHubEmail: "sammiat49@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "49",
    name: "Familiar Stranger",
    username: "Stranger",
    workspaceEmail: "olaniyi42g@gmail.com",
    gitHubEmail: "olaniyi42g@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "50",
    name: "Nsikak Sunday",
    username: "Nk",
    workspaceEmail: "nsikakmbre@gmail.com",
    gitHubEmail: "nsikakmbre@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "51",
    name: "Ayomide Abayomi Oluwanifemi",
    username: "ayomide abayomi",
    workspaceEmail: "abayomiayomid5@gmail.com",
    gitHubEmail: "abayomiayomid5@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "52",
    name: "Adebanjo Israel",
    username: "@debanjo_israel",
    workspaceEmail: "debanjo31@gmail.com",
    gitHubEmail: "debanjo31@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "53",
    name: "Charles Chioma",
    username: "Charles nifemi",
    workspaceEmail: "nifemicharles6@gmail.com",
    gitHubEmail: "N/A",
    role: "member",
    hobbies: [],
  },
  {
    id: "54",
    name: "Emaye Andrew",
    username: "Andycooo",
    workspaceEmail: "G.emaye01@gmail.com",
    gitHubEmail: "G.emaye@live.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "55",
    name: "Felicia",
    username: "Kowontan",
    workspaceEmail: "bunmiadejoke1@yahoo.com",
    gitHubEmail: "bunmiadejoke1@yahoo.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "56",
    name: "Oyebimpe Shittu",
    username: "Oyebimpe Shittu",
    workspaceEmail: "oyebimpeshi2@gmail.com",
    gitHubEmail: "shittuoyebimpe@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "57",
    name: "Olamide Afolayan",
    username: "Olamide Afolayan",
    workspaceEmail: "olamideafolayan17@gmail.com",
    gitHubEmail: "olamideafolayan17@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "58",
    name: "Precious Chinalu Chijioke",
    username: "Precious Chijioke",
    workspaceEmail: "chijiokeprecious51@gmail.com",
    gitHubEmail: "preciouschijioke998@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "59",
    name: "Ugbomah Daniel",
    username: "ugbomah daniel",
    workspaceEmail: "danielugbomaht@gmail.com",
    gitHubEmail: "Ugbomah-D",
    role: "member",
    hobbies: ["Reading", "Chess", "Coding"],
  },
  {
    id: "60",
    name: "Oluwatosin Enoch Ogunfusika",
    username: "Enoch",
    workspaceEmail: "enochogunfusika@gmail.com",
    gitHubEmail: "enochogunfusika@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "61",
    name: "stephen Ebube",
    username: "Stephen Ebube",
    workspaceEmail: "stephenebube01@gmail.com",
    gitHubEmail: "Jstepcode",
    role: "member",
    hobbies: [],
  },
  {
    id: "62",
    name: "maram",
    username: "maram",
    workspaceEmail: "maramemad674@gmail.com",
    gitHubEmail: "maramemad674@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "63",
    name: "Adeniyi Peter",
    username: "adeniyi peter",
    workspaceEmail: "adeniyipeter999@gmail.com",
    gitHubEmail: "adeniyipeter999@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "64",
    name: "Nwosu NKEMJIKA ANTHONIA",
    username: "Tonia",
    workspaceEmail: "nwosunkemjika1@gmail.com",
    gitHubEmail: "nwosunkemjika1@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "65",
    name: "Eze Vivian Munachi",
    username: "eze vivian",
    workspaceEmail: "ezevivian400@gmail.com",
    gitHubEmail: "ezevivian400@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "66",
    name: "Chidinma Onyeneke",
    username: "Dinma.onyeneke",
    workspaceEmail: "dinma.onyeneke@gmail.com",
    gitHubEmail: "dinma.onyeneke@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "67",
    name: "Gbadebo Samuel",
    username: "Dinolabs",
    workspaceEmail: "ultimatedeeno@gmail.com",
    gitHubEmail: "ultimatedeeno@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "68",
    name: "Raphael Ifeanyi Eze",
    username: "Raphblink",
    workspaceEmail: "raphblink@gmail.com",
    gitHubEmail: "raphaelifeanyieze@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "69",
    name: "OBISESAN ADEWALE",
    username: "MUYIWA ADEWALE",
    workspaceEmail: "muyiwaadewale75@gmail.com",
    gitHubEmail: "muyiwaadewale75@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "70",
    name: "Ifeoluwa Adeniran",
    username: "Debo",
    workspaceEmail: "deniranifeoluwa@gmail.com",
    gitHubEmail: "deniranifeoluwa@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "71",
    name: "Ibrahim Adebayo",
    username: "Khalileluno",
    workspaceEmail: "sijuadebayo@gmail.com",
    gitHubEmail: "sijuadebayo@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "72",
    name: "Beatrice Pepple",
    username: "beatricepepple",
    workspaceEmail: "beatrice.pepple@gmail.com",
    gitHubEmail: "beatrice.pepple@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "73",
    name: "ENOCH MANCHA",
    username: "enoch",
    workspaceEmail: "peratenoch@gmail.com",
    gitHubEmail: "peratenoch@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "74",
    name: "Ridwan Wahab Olalekan",
    username: "Ridwan",
    workspaceEmail: "ridwonwahab@gmail.com",
    gitHubEmail: "ridwonwahab@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "75",
    name: "Goodness Abasiakama Bassey",
    username: "goodness bassey",
    workspaceEmail: "goodnessbassey003@gmail.com",
    gitHubEmail: "goodnessbassey003@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "76",
    name: "Ekanem Victor",
    username: "Ekanem Victor",
    workspaceEmail: "ekanvicky@gmail.com",
    gitHubEmail: "ekanvicky@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "77",
    name: "Jeremiah Abiona",
    username: "jayT",
    workspaceEmail: "jeremiahayoola350@gmail.com",
    gitHubEmail: "jeremiahayoola350@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "78",
    name: "Nwafor Gabriel",
    username: "nwafor gabriel",
    workspaceEmail: "mmaduabuchigabriel88@gmail.com",
    gitHubEmail: "gabrielmmaduabuchi01@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "79",
    name: "Ekwere Noble Nathan",
    username: "@ekwere_noble",
    workspaceEmail: "ekwerenoble2@gmail.com",
    gitHubEmail: "ekwerenoble2@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "80",
    name: "Wisdom Ovhemerutho-athe",
    username: "mrwizzy",
    workspaceEmail: "mrwhizzy1@gmail.com",
    gitHubEmail: "mrwhizzy1@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "81",
    name: "keyu oje",
    username: "keyu oje",
    workspaceEmail: "ojekevin4@gmail.com",
    gitHubEmail: "ojekevin4@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "82",
    name: "Agbajelola Habeebullah Temitope",
    username: "Agbajelola Habeebullah",
    workspaceEmail: "Agbajelolah@gmail.com",
    gitHubEmail: "Agbajelolah@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "83",
    name: "Daniel Jegbefumhen",
    username: "Daniel J",
    workspaceEmail: "jegbefumhendaniel@gmail.com",
    gitHubEmail: "jegbefumhendaniel@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "84",
    name: "Olujinmi Oluwafemi",
    username: "Olujinmi Oluwafemi",
    workspaceEmail: "olujinmioluwafemi@gmail.com",
    gitHubEmail: "olujinmioluwafemi@gmail.com",
    role: "member",
    hobbies: ["Reading", "Coding", "Traveling"],
  },
  {
    id: "85",
    name: "Kehinde James",
    username: "Leke",
    workspaceEmail: "jameskehinde101@gmail.com",
    gitHubEmail: "jameskehinde101@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "86",
    name: "NDUBUISI Chukwuwmeka Michael",
    username: "chukzmiki",
    workspaceEmail: "chukzmichael@gmail.com",
    gitHubEmail: "chukzmichael@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "87",
    name: "Victor Igbokwe",
    username: "Meysdays",
    workspaceEmail: "igbokwevictor122@gmail.com",
    gitHubEmail: "igbokwevictor122@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "88",
    name: "ABDULAZEEZ Ibraheem Gbolahan",
    username: "ibraheem abdulazeez",
    workspaceEmail: "abdulazeezibraheem68@gmail.com",
    gitHubEmail: "abdulazeezibraheem68@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "89",
    name: "Samuel Gbadebo",
    username: "Samuel Gbadebo",
    workspaceEmail: "samueltomisin31@gmail.com",
    gitHubEmail: "samueltomisin31@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "90",
    name: "Mustapha Oyenuga",
    username: "Mustapha Oyenuga",
    workspaceEmail: "musty1k4real@gmail.com",
    gitHubEmail: "musty1k@yahoo.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "91",
    name: "Maya Aliya",
    username: "Maya Aliya",
    workspaceEmail: "mabellaliya1@gmail.com",
    gitHubEmail: "mabellaliya1@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "92",
    name: "Awoke Emmanuel",
    username: "awokeEmmanuel",
    workspaceEmail: "emmanuelawoke665@gmail.com",
    gitHubEmail: "emmanuelawoke665@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "93",
    name: "Iderima Daniel",
    username: "Daniel Iderima",
    workspaceEmail: "iderimadanye@gmail.com",
    gitHubEmail: "iderimadanye@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "94",
    name: "Obimba Samuel",
    username: "Obimz",
    workspaceEmail: "samuelobimbaawesome@gmail.com",
    gitHubEmail: "samuelobimbaawesome@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "95",
    name: "David Omage",
    username: "Dayve007",
    workspaceEmail: "davillamags007@gmail.com",
    gitHubEmail: "davidomage@yahoo.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "96",
    name: "Ekoyi Amity Tobi",
    username: "amity",
    workspaceEmail: "amityekoyi@gmail.com",
    gitHubEmail: "amityekoyi@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "97",
    name: "Joshua Emenike",
    username: "Joshua ndu",
    workspaceEmail: "Joshuandu3@gmail.com",
    gitHubEmail: "joshuandu3@gmail.com",
    role: "member",
    hobbies: [],
  },
  {
    id: "98",
    name: "Chinenye Onwuzulike",
    username: "ChinenyeOnwuzulike",
    workspaceEmail: "chinenyeonwuzulike99@gmail.com",
    gitHubEmail: "chinenyeonwuzulike99@gmail.com",
    role: "member",
    hobbies: [],
  },
];

export default function MacawPage() {
  return (
    <div className="min-h-screen">
      {/* Hero */}
      <section className="relative isolate flex w-full flex-col items-center gap-5 overflow-hidden px-4 py-12 text-center sm:gap-6 sm:px-8 sm:py-16 lg:gap-8 lg:px-12">
        <div className="absolute inset-0 -z-10 size-full max-h-screen bg-blue-50/2" />
        <div className="flex flex-col items-center gap-3">
          <span className="inline-block w-fit rounded-full bg-primary-50/50 px-4 py-1.5 text-xs font-medium text-primary-500 sm:text-sm">
            Macaw Release
          </span>
          <h1 className="text-2xl font-semibold leading-tight text-neutral-900 sm:text-3xl md:text-4xl text-center">
            Zedu <span className="text-primary-500">Macaw</span> Contributors
          </h1>
          <p className="max-w-[95%] text-sm text-neutral-600 sm:max-w-[90%] sm:text-base md:max-w-[85%] lg:max-w-[65%] lg:text-lg">
            A heartfelt thank you to everyone who contributed their time, ideas,
            and craft to the Macaw release.
          </p>
        </div>
      </section>

      {/* Contributors grid */}
      <section className="w-full px-4 pb-12 sm:px-8 sm:pb-16 lg:px-12">
        <ContributorsList contributors={contributors} />
      </section>

      <DynamicFooter
        text="Built by the Zedu Community"
        description="Join the contributors shaping the future of structured, AI-assisted learning."
      />
    </div>
  );
}
