import type { Metadata } from "next";
import { DynamicFooter } from "../../_components/footer/dynamic-footer";
import {
  ContributorCard,
  type Contributor,
} from "./_components/contributor-card";
import { ContributorsList } from "./_components/contributors-list";

export const metadata: Metadata = {
  title: "Zedu Macaw Contributors",
  description:
    "Meet the contributors who helped build the Zedu Macaw release - the designers, engineers, and community members shaping modern learning.",
  keywords: [
    "Zedu contributors",
    "Zedu Macaw",
    "open source contributors",
    "learning platform contributors",
    "Zedu community",
  ],
  openGraph: {
    title: "Zedu Macaw Contributors",
    description:
      "A thank you to everyone who contributed to the Zedu Macaw release.",
    url: "/contributors/macaw",
    siteName: "Zedu",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Zedu Macaw Contributors",
    description:
      "A thank you to everyone who contributed to the Zedu Macaw release.",
  },
  alternates: {
    canonical: "/contributors/macaw",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const contributors: Contributor[] = [
  {
    name: "Chisom Aniekwensi",
    username: "ChisomAniekwensi",
    workspaceEmail: "sommaniekwensi@gmail.com",
    gitHubEmail: "sommaniekwensi@gmail.com",
    role: "Team Lead",
  },
  {
    name: "Olaleye Obidiya",
    username: "onyx_oceanview",
    workspaceEmail: "olaleyeobidiya@gmail.com",
    gitHubEmail: "olaleyeobidiya@gmail.com",
    role: "technical lead",
  },
  {
    name: "Okoro Theresa Chioma",
    username: "okorotheresa149-spec",
    workspaceEmail: "Okorotessy149@gmail.com",
    gitHubEmail: "okorotessy149@gmail.com",
    role: "member",
  },
  {
    name: "Azeezah Fasasi",
    username: "azeezah fasasi",
    workspaceEmail: "fas4azeezah@gmail.com",
    gitHubEmail: "fas4azeezah@gmail.com",
    role: "member",
  },
  {
    name: "Oluwasegun Ikoya",
    username: "OluwasegunIkoya",
    workspaceEmail: "oluwasegunikoya@gmail.com",
    gitHubEmail: "emmanuelikoya99@gmail.com",
    role: "member",
  },
  {
    name: "Muhammad Abdullahi Makarfi",
    username: "Muhammad Abdullahi Makarfi",
    workspaceEmail: "ma9008180@gmail.com",
    gitHubEmail: "ma9008180@gmail.com",
    role: "member",
  },
  {
    name: "Ojeaburu wisdom Omogafen",
    username: "Wisdom Ojeaburu",
    workspaceEmail: "wisojeaburu@gmail.com",
    gitHubEmail: "peroprimus1234@gmail.com",
    role: "member",
  },
  {
    name: "Fredrick Vivian Chizoba",
    username: "Vivian Chizoba Fredrick",
    workspaceEmail: "fredrickvivian057@gmail.com",
    gitHubEmail: "fredrickvivian057@gmail.com",
    role: "member",
  },
  {
    name: "Lasisi Oluwatimilehin Joshua",
    username: "Lasisi Oluwatimilehin Joshua",
    workspaceEmail: "lasisitimilehin9@gmail.com",
    gitHubEmail: "lasisitimilehin9@gmail.com",
    role: "member",
  },
  {
    name: "Akinwande Joseph Obiti",
    username: "akinwandeobiti",
    workspaceEmail: "akinwandeobiti@gmail.com",
    gitHubEmail: "obitiakinwandeno1@gmail.com",
    role: "member",
  },
  {
    name: "Afolarin Segun Sunday",
    username: "Mash",
    workspaceEmail: "afolarinsegun@gmail.com",
    gitHubEmail: "afolarinsegun@gmail.com",
    role: "member",
  },
  {
    name: "Abonyi Izuvhukwu",
    username: "Izuchukwu",
    workspaceEmail: "abonyiizuchukwu@gmail.com",
    gitHubEmail: "abonyiizuchukwu@gmail.com",
    role: "member",
  },
  {
    name: "Ngozi Orji",
    username: "Blizz",
    workspaceEmail: "ngoziorji75@gmail.com",
    gitHubEmail: "ngoziorji75@gmail.com",
    role: "member",
  },
  {
    name: "Tochukwu Obinna",
    username: "Tunchi-0805",
    workspaceEmail: "tunchiprova@gmail.com",
    gitHubEmail: "Sijoshleon@gmail.com",
    role: "member",
  },
  {
    name: "Olatuja Victor Toluwanimi",
    username: "vance",
    workspaceEmail: "mrxxvector@gmail.com",
    gitHubEmail: "mrxxvector@gmail.com",
    role: "member",
  },
  {
    name: "Michael Felix",
    username: "Michael Felix",
    workspaceEmail: "mikelphelix@gmail.com",
    gitHubEmail: "agboolaademichael@gmail.com",
    role: "member",
  },
  {
    name: "Umeh chinonye Juliet",
    username: "Chinonye Umeh",
    workspaceEmail: "Chinonyejulz@gmail.com",
    gitHubEmail: "Chinonyejulz@gmail.com",
    role: "member",
  },
  {
    name: "Grace Oyemade",
    username: "@graceoyemade",
    workspaceEmail: "graceopeoyemade@gmail.com",
    gitHubEmail: "graceopeoyemade@gmail.com",
    role: "member",
  },
  {
    name: "King Jaleel",
    username: "Jaleel",
    workspaceEmail: "odetolababs@gmail.com",
    gitHubEmail: "sirfunsho",
    role: "member",
  },
  {
    name: "Muhammad Alameen Adamu",
    username: "Alameentoro",
    workspaceEmail: "muhammadtt97@gmail.com",
    gitHubEmail: "muhammadtt97@gmail.com",
    role: "member",
  },
  {
    name: "Stephen Omachonu",
    username: "stephen omachonu",
    workspaceEmail: "stephomac89@gmail.com",
    gitHubEmail: "somachonu.2302393@stu.cu.edu.ng",
    role: "member",
  },
  {
    name: "Yusuf Muhammad Musa",
    username: "yusuufmm",
    workspaceEmail: "yusuf2000mm@gmail.com",
    gitHubEmail: "yusuf2000mm@gmail.com",
    role: "member",
  },
  {
    name: "Ikemefuna Nwodo",
    username: "Ikemefuna nwodo",
    workspaceEmail: "Nwodofrank@gmail.com",
    gitHubEmail: "Nwodofrank@gmail.com",
    role: "member",
  },
  {
    name: "daniel field",
    username: "danchofield1",
    workspaceEmail: "danchofield1@yahoo.com",
    gitHubEmail: "Fieldpresido1",
    role: "member",
  },
  {
    name: "Oyelami Sekinat Ebunoluwa",
    username: "GiftyHealthTech",
    workspaceEmail: "sekinatoyelami@gmail.com",
    gitHubEmail: "sekinatoyelami@gmail.com",
    role: "member",
  },
  {
    name: "Priscilla Bertley",
    username: "bertley priscy",
    workspaceEmail: "bertleypriscy@gmail.com",
    gitHubEmail: "bertleypriscy@gmail.com",
    role: "member",
  },
  {
    name: "Samson Ocran",
    username: "Samson Ocran",
    workspaceEmail: "samson.ocran@gmail.com",
    gitHubEmail: "samson.ocran@gmail.com",
    role: "member",
  },
  {
    name: "Olapite Oluwadolapo",
    username: "Dolappy",
    workspaceEmail: "olapitedolapo@gmail.com",
    gitHubEmail: "olapitedolapo@gmail.com",
    role: "member",
  },
  {
    name: "Joshua",
    username: "Jboy",
    workspaceEmail: "onitimilehin87@gmail.com",
    gitHubEmail: "onitimilehin87@gmail.com",
    role: "member",
  },
  {
    name: "Mustapha Bashir",
    username: "@mustapha_bashir",
    workspaceEmail: "mustaphabashir348@gmail.com",
    gitHubEmail: "mustaphabashir348@gmail.com",
    role: "member",
  },
  {
    name: "Abdulganiyu Abu",
    username: "ganiyu ganiyu_01a0ca1c",
    workspaceEmail: "Ganiyuabu2@gmail.com",
    gitHubEmail: "Ganiyuabu2@gmail.com",
    role: "member",
  },
  {
    name: "Ciary Ben Alok",
    username: "ciaryben623",
    workspaceEmail: "ciaryben623@gmail.com",
    gitHubEmail: "ciaryben623@gmail.com",
    role: "member",
  },
  {
    name: "Adetunji Abosede Esther",
    username: "Tema",
    workspaceEmail: "adetunjibose2018@gmail.com",
    gitHubEmail: "adetunjibose2018@gmail.com",
    role: "member",
  },
  {
    name: "Ijeoma Egbeke",
    username: "Ijeoma Egbeke",
    workspaceEmail: "ijeomaegbeke@gmail.com",
    gitHubEmail: "ijeomaegbeke@gmail.com",
    role: "member",
  },
  {
    name: "Muhammad Abdullahi Kutigi",
    username: "Muhammad_Kutigi",
    workspaceEmail: "muhammadkutigi90@gmail.com",
    gitHubEmail: "muhammadkutigi90@gmail.com",
    role: "member",
  },
  {
    name: "Paul Momoh",
    username: "boootconverse",
    workspaceEmail: "boootconverse@gmail.com",
    gitHubEmail: "dumeccs@gmail.com",
    role: "member",
  },
  {
    name: "Okoli Chidozie Kingsley",
    username: "Chidozie",
    workspaceEmail: "chidozie4god@gmail.com",
    gitHubEmail: "chidozie4god@gmail.com",
    role: "member",
  },
  {
    name: "Nwodo Destiny",
    username: "destiny nwodo",
    workspaceEmail: "dessynwodo@gmail.com",
    gitHubEmail: "dessynwodo@gmail.com",
    role: "member",
  },
  {
    name: "Joel Nwaelugo",
    username: "joelnwaelugo",
    workspaceEmail: "joelnwaelugo@gmail.com",
    gitHubEmail: "joelnwaelugo@gmail.com",
    role: "member",
  },
  {
    name: "Funsho Kamoru",
    username: "Funsho",
    workspaceEmail: "funshoamoru@gmail.com",
    gitHubEmail: "funshokamoru@gmail.com",
    role: "member",
  },
  {
    name: "Chioma Esther Okpor",
    username: "Chioma Okpor",
    workspaceEmail: "estee.ojumah@gmail.com",
    gitHubEmail: "estee.ojumah@gmail.com",
    role: "member",
  },
  {
    name: "Kenneth okonkwo",
    username: "Kenneth okonkwo",
    workspaceEmail: "kennethokonkwo73@gmail.com",
    gitHubEmail: "kennethokonkwo73@gmail.com",
    role: "member",
  },
  {
    name: "Chiamaka Favour Amaechi",
    username: "chifav",
    workspaceEmail: "chifav312@gmail.com",
    gitHubEmail: "chifav312@gmail.com",
    role: "member",
  },
  {
    name: "Oluwakorede Serah Banfe",
    username: "Holuwahkorede",
    workspaceEmail: "holuwahkoredebanfe@gmail.com",
    gitHubEmail: "oluwakoredebanfe@gmail.com",
    role: "member",
  },
  {
    name: "Oki Blessing",
    username: "blessingoki94",
    workspaceEmail: "blessingoki94@gmail.com",
    gitHubEmail: "blessingoki94@gmail.com",
    role: "member",
  },
  {
    name: "ArnoldNyamongo",
    username: "ArnoldNyamongo",
    workspaceEmail: "arnoldnyams@gmail.com",
    gitHubEmail: "arnoldnyams@gmail.com",
    role: "member",
  },
  {
    name: "Iniobong Ekpenyong",
    username: "iniobong ekpenyong",
    workspaceEmail: "iniobongmichaelekpenyong@gmail.com",
    gitHubEmail: "iniobongmichaelekpenyong@gmail.com",
    role: "member",
  },
  {
    name: "Shittu Sammiat Ayomide",
    username: "Sammiat49",
    workspaceEmail: "sammiat49@gmail.com",
    gitHubEmail: "sammiat49@gmail.com",
    role: "member",
  },
  {
    name: "Familiar Stranger",
    username: "Stranger",
    workspaceEmail: "olaniyi42g@gmail.com",
    gitHubEmail: "olaniyi42g@gmail.com",
    role: "member",
  },
  {
    name: "Nsikak Sunday",
    username: "Nk",
    workspaceEmail: "nsikakmbre@gmail.com",
    gitHubEmail: "nsikakmbre@gmail.com",
    role: "member",
  },
  {
    name: "Ayomide Abayomi Oluwanifemi",
    username: "ayomide abayomi",
    workspaceEmail: "abayomiayomid5@gmail.com",
    gitHubEmail: "abayomiayomid5@gmail.com",
    role: "member",
  },
  {
    name: "Adebanjo Israel",
    username: "@debanjo_israel",
    workspaceEmail: "debanjo31@gmail.com",
    gitHubEmail: "debanjo31@gmail.com",
    role: "member",
  },
  {
    name: "Charles Chioma",
    username: "Charles nifemi",
    workspaceEmail: "nifemicharles6@gmail.com",
    gitHubEmail: "N/A",
    role: "member",
  },
  {
    name: "Emaye Andrew",
    username: "Andycooo",
    workspaceEmail: "G.emaye01@gmail.com",
    gitHubEmail: "G.emaye@live.com",
    role: "member",
  },
  {
    name: "Felicia",
    username: "Kowontan",
    workspaceEmail: "bunmiadejoke1@yahoo.com",
    gitHubEmail: "bunmiadejoke1@yahoo.com",
    role: "member",
  },
  {
    name: "Oyebimpe Shittu",
    username: "Oyebimpe Shittu",
    workspaceEmail: "oyebimpeshi2@gmail.com",
    gitHubEmail: "shittuoyebimpe@gmail.com",
    role: "member",
  },
  {
    name: "Olamide Afolayan",
    username: "Olamide Afolayan",
    workspaceEmail: "olamideafolayan17@gmail.com",
    gitHubEmail: "olamideafolayan17@gmail.com",
    role: "member",
  },
  {
    name: "Precious Chinalu Chijioke",
    username: "Precious Chijioke",
    workspaceEmail: "chijiokeprecious51@gmail.com",
    gitHubEmail: "preciouschijioke998@gmail.com",
    role: "member",
  },
  {
    name: "Ugbomah Daniel",
    username: "ugbomah daniel",
    workspaceEmail: "danielugbomaht@gmail.com",
    gitHubEmail: "Ugbomah-D",
    role: "member",
  },
  {
    name: "Oluwatosin Enoch Ogunfusika",
    username: "Enoch",
    workspaceEmail: "enochogunfusika@gmail.com",
    gitHubEmail: "enochogunfusika@gmail.com",
    role: "member",
  },
  {
    name: "stephen Ebube",
    username: "Stephen Ebube",
    workspaceEmail: "stephenebube01@gmail.com",
    gitHubEmail: "Jstepcode",
    role: "member",
  },
  {
    name: "maram",
    username: "maram",
    workspaceEmail: "maramemad674@gmail.com",
    gitHubEmail: "maramemad674@gmail.com",
    role: "member",
  },
  {
    name: "Adeniyi Peter",
    username: "adeniyi peter",
    workspaceEmail: "adeniyipeter999@gmail.com",
    gitHubEmail: "adeniyipeter999@gmail.com",
    role: "member",
  },
  {
    name: "Nwosu NKEMJIKA ANTHONIA",
    username: "Tonia",
    workspaceEmail: "nwosunkemjika1@gmail.com",
    gitHubEmail: "nwosunkemjika1@gmail.com",
    role: "member",
  },
  {
    name: "Eze Vivian Munachi",
    username: "eze vivian",
    workspaceEmail: "ezevivian400@gmail.com",
    gitHubEmail: "ezevivian400@gmail.com",
    role: "member",
  },
  {
    name: "Chidinma Onyeneke",
    username: "Dinma.onyeneke",
    workspaceEmail: "dinma.onyeneke@gmail.com",
    gitHubEmail: "dinma.onyeneke@gmail.com",
    role: "member",
  },
  {
    name: "Gbadebo Samuel",
    username: "Dinolabs",
    workspaceEmail: "ultimatedeeno@gmail.com",
    gitHubEmail: "ultimatedeeno@gmail.com",
    role: "member",
  },
  {
    name: "Raphael Ifeanyi Eze",
    username: "Raphblink",
    workspaceEmail: "raphblink@gmail.com",
    gitHubEmail: "raphaelifeanyieze@gmail.com",
    role: "member",
  },
  {
    name: "OBISESAN ADEWALE",
    username: "MUYIWA ADEWALE",
    workspaceEmail: "muyiwaadewale75@gmail.com",
    gitHubEmail: "muyiwaadewale75@gmail.com",
    role: "member",
  },
  {
    name: "Ifeoluwa Adeniran",
    username: "Debo",
    workspaceEmail: "deniranifeoluwa@gmail.com",
    gitHubEmail: "deniranifeoluwa@gmail.com",
    role: "member",
  },
  {
    name: "Ibrahim Adebayo",
    username: "Khalileluno",
    workspaceEmail: "sijuadebayo@gmail.com",
    gitHubEmail: "sijuadebayo@gmail.com",
    role: "member",
  },
  {
    name: "Beatrice Pepple",
    username: "beatricepepple",
    workspaceEmail: "beatrice.pepple@gmail.com",
    gitHubEmail: "beatrice.pepple@gmail.com",
    role: "member",
  },
  {
    name: "ENOCH MANCHA",
    username: "enoch",
    workspaceEmail: "peratenoch@gmail.com",
    gitHubEmail: "peratenoch@gmail.com",
    role: "member",
  },
  {
    name: "Ridwan Wahab Olalekan",
    username: "Ridwan",
    workspaceEmail: "ridwonwahab@gmail.com",
    gitHubEmail: "ridwonwahab@gmail.com",
    role: "member",
  },
  {
    name: "Goodness Abasiakama Bassey",
    username: "goodness bassey",
    workspaceEmail: "goodnessbassey003@gmail.com",
    gitHubEmail: "goodnessbassey003@gmail.com",
    role: "member",
  },
  {
    name: "Ekanem Victor",
    username: "Ekanem Victor",
    workspaceEmail: "ekanvicky@gmail.com",
    gitHubEmail: "ekanvicky@gmail.com",
    role: "member",
  },
  {
    name: "Jeremiah Abiona",
    username: "jayT",
    workspaceEmail: "jeremiahayoola350@gmail.com",
    gitHubEmail: "jeremiahayoola350@gmail.com",
    role: "member",
  },
  {
    name: "Nwafor Gabriel",
    username: "nwafor gabriel",
    workspaceEmail: "mmaduabuchigabriel88@gmail.com",
    gitHubEmail: "gabrielmmaduabuchi01@gmail.com",
    role: "member",
  },
  {
    name: "Ekwere Noble Nathan",
    username: "@ekwere_noble",
    workspaceEmail: "ekwerenoble2@gmail.com",
    gitHubEmail: "ekwerenoble2@gmail.com",
    role: "member",
  },
  {
    name: "Wisdom Ovhemerutho-athe",
    username: "mrwizzy",
    workspaceEmail: "mrwhizzy1@gmail.com",
    gitHubEmail: "mrwhizzy1@gmail.com",
    role: "member",
  },
  {
    name: "keyu oje",
    username: "keyu oje",
    workspaceEmail: "ojekevin4@gmail.com",
    gitHubEmail: "ojekevin4@gmail.com",
    role: "member",
  },
  {
    name: "Agbajelola Habeebullah Temitope",
    username: "Agbajelola Habeebullah",
    workspaceEmail: "Agbajelolah@gmail.com",
    gitHubEmail: "Agbajelolah@gmail.com",
    role: "member",
  },
  {
    name: "Daniel Jegbefumhen",
    username: "Daniel J",
    workspaceEmail: "jegbefumhendaniel@gmail.com",
    gitHubEmail: "jegbefumhendaniel@gmail.com",
    role: "member",
  },
  {
    name: "Olujinmi Oluwafemi",
    username: "Olujinmi Oluwafemi",
    workspaceEmail: "olujinmioluwafemi@gmail.com",
    gitHubEmail: "olujinmioluwafemi@gmail.com",
    role: "member",
  },
  {
    name: "Kehinde James",
    username: "Leke",
    workspaceEmail: "jameskehinde101@gmail.com",
    gitHubEmail: "jameskehinde101@gmail.com",
    role: "member",
  },
  {
    name: "NDUBUISI Chukwuwmeka Michael",
    username: "chukzmiki",
    workspaceEmail: "chukzmichael@gmail.com",
    gitHubEmail: "chukzmichael@gmail.com",
    role: "member",
  },
  {
    name: "Victor Igbokwe",
    username: "Meysdays",
    workspaceEmail: "igbokwevictor122@gmail.com",
    gitHubEmail: "igbokwevictor122@gmail.com",
    role: "member",
  },
  {
    name: "ABDULAZEEZ Ibraheem Gbolahan",
    username: "ibraheem abdulazeez",
    workspaceEmail: "abdulazeezibraheem68@gmail.com",
    gitHubEmail: "abdulazeezibraheem68@gmail.com",
    role: "member",
  },
  {
    name: "Samuel Gbadebo",
    username: "Samuel Gbadebo",
    workspaceEmail: "samueltomisin31@gmail.com",
    gitHubEmail: "samueltomisin31@gmail.com",
    role: "member",
  },
  {
    name: "Mustapha Oyenuga",
    username: "Mustapha Oyenuga",
    workspaceEmail: "musty1k4real@gmail.com",
    gitHubEmail: "musty1k@yahoo.com",
    role: "member",
  },
  {
    name: "Maya Aliya",
    username: "Maya Aliya",
    workspaceEmail: "mabellaliya1@gmail.com",
    gitHubEmail: "mabellaliya1@gmail.com",
    role: "member",
  },
  {
    name: "Awoke Emmanuel",
    username: "awokeEmmanuel",
    workspaceEmail: "emmanuelawoke665@gmail.com",
    gitHubEmail: "emmanuelawoke665@gmail.com",
    role: "member",
  },
  {
    name: "Iderima Daniel",
    username: "Daniel Iderima",
    workspaceEmail: "iderimadanye@gmail.com",
    gitHubEmail: "iderimadanye@gmail.com",
    role: "member",
  },
  {
    name: "Obimba Samuel",
    username: "Obimz",
    workspaceEmail: "samuelobimbaawesome@gmail.com",
    gitHubEmail: "samuelobimbaawesome@gmail.com",
    role: "member",
  },
  {
    name: "David Omage",
    username: "Dayve007",
    workspaceEmail: "davillamags007@gmail.com",
    gitHubEmail: "davidomage@yahoo.com",
    role: "member",
  },
  {
    name: "Ekoyi Amity Tobi",
    username: "amity",
    workspaceEmail: "amityekoyi@gmail.com",
    gitHubEmail: "amityekoyi@gmail.com",
    role: "member",
  },
  {
    name: "Joshua Emenike",
    username: "Joshua ndu",
    workspaceEmail: "Joshuandu3@gmail.com",
    gitHubEmail: "joshuandu3@gmail.com",
    role: "member",
  },
];

export default function MacawPage() {
  return (
    <div className="min-h-screen">
      {/* Hero */}
      <section className="relative isolate flex w-full flex-col items-center gap-5 overflow-hidden px-4 py-12 text-center sm:gap-6 sm:px-8 sm:py-16 lg:gap-8 lg:px-12">
        <div className="absolute inset-0 -z-10 size-full max-h-screen bg-blue-50/2" />
        <div className="flex flex-col items-center gap-3">
          <span className="inline-block w-fit rounded-full bg-primary-50/50 px-4 py-1.5 text-xs font-medium text-primary-500 sm:text-sm">
            Macaw Release
          </span>
          <h1 className="text-2xl font-semibold leading-tight text-neutral-900 sm:text-3xl md:text-4xl text-center">
            Zedu <span className="text-primary-500">Macaw</span> Contributors
          </h1>
          <p className="max-w-[95%] text-sm text-neutral-600 sm:max-w-[90%] sm:text-base md:max-w-[85%] lg:max-w-[65%] lg:text-lg">
            A heartfelt thank you to everyone who contributed their time, ideas,
            and craft to the Macaw release.
          </p>
        </div>
      </section>

      {/* Contributors grid */}
      <ContributorsList contributors={contributors} />

      <DynamicFooter
        text="Built by the Zedu Community"
        description="Join the contributors shaping the future of structured, AI-assisted learning."
      />
    </div>
  );
}
