export interface Contributor {
  id: string;
  name: string;
  username: string;
  zeduName: string;
  background: string;
  email: string;
  linkedin?: string;
  avatarGradient: string;
}

export const contributors: Contributor[] = [
  {
    id: "kestrel-01",
    name: "Jefferson Yankson",
    username: "jeff yankson",
    zeduName: "jeff yankson",
    background: "Backend Developer",
    email: "jjyankson19@gmail.com",
    avatarGradient: "from-primary-500 to-blue-400",
  },
  {
    id: "kestrel-02",
    name: "Collins Adimabuia Odogwu",
    username: "Collins Odogwu",
    zeduName: "Collins Odogwu",
    background: "Data Analysis",
    email: "collinsodogwu642@gmail.com",
    linkedin: "collins-odogwu303",
    avatarGradient: "from-secondary-500 to-tertiary-400",
  },
  {
    id: "kestrel-03",
    name: "Owonifari Ajibola",
    username: "Global",
    zeduName: "Global",
    background: "Quality Assurance Engineer / Tester",
    email: "ajibolaowonifari@gmail.com",
    linkedin: "ajibola-owonifari",
    avatarGradient: "from-primary-400 to-secondary-500",
  },
  {
    id: "kestrel-04",
    name: "Ruth Nnamani",
    username: "TechBaby",
    zeduName: "TechBaby",
    background: "Project Manager / Virtual Assistant",
    email: "eruby4453@gmail.com",
    linkedin: "ruth7135",
    avatarGradient: "from-alert-400 to-primary-500",
  },
  {
    id: "kestrel-05",
    name: "Mbuotidem Okon",
    username: "Design Sensei",
    zeduName: "Design Sensei",
    background: "UI/UX & AI Developer",
    email: "Faithokon007@gmail.com",
    avatarGradient: "from-blue-400 to-primary-500",
  },
  {
    id: "kestrel-06",
    name: "Otega Otite",
    username: "otega_otite",
    zeduName: "otega_otite",
    background: "Full-Stack Developer",
    email: "otiteotega@gmail.com",
    avatarGradient: "from-tertiary-500 to-primary-400",
  },
  {
    id: "kestrel-07",
    name: "Ihejirika Blessing Onyinye",
    username: "Onyinyechukwu",
    zeduName: "Onyinyechukwu",
    background: "Backend Developer",
    email: "onyinyechukwumblessing@gmail.com",
    avatarGradient: "from-blue-500 to-secondary-400",
  },
  {
    id: "kestrel-08",
    name: "Oparaocha Ogochukwu Mercy",
    username: "Ogos",
    zeduName: "Ogos",
    background: "Frontend Engineering",
    email: "oparaochaogochukwumercy@gmail.com",
    linkedin: "ogochukwu-oparaocha",
    avatarGradient: "from-primary-500 to-alert-400",
  },
  {
    id: "kestrel-09",
    name: "Adeniran ISREAL kehinde",
    username: "Kenny Gee",
    zeduName: "Kenny Gee",
    background: "Graphics Designer",
    email: "kennygee908@gmail.com",
    avatarGradient: "from-secondary-500 to-primary-400",
  },
  {
    id: "kestrel-10",
    name: "Basit Olarewaju Salaudeen",
    username: "BASIT",
    zeduName: "BASIT",
    background: "Virtual Assistant",
    email: "Salaudeenbasit521@gmail.com",
    avatarGradient: "from-primary-500 to-secondary-400",
  },
  {
    id: "kestrel-11",
    name: "Ochuba Daniel Ifeanyi",
    username: "Daniel Ifeanyi",
    zeduName: "Daniel Ifeanyi",
    background: "Software Engineer",
    email: "danielifeanyi74@gmail.com",
    linkedin: "daniel-ifeanyi-b33931325",
    avatarGradient: "from-blue-500 to-primary-400",
  },
  {
    id: "kestrel-12",
    name: "Silvia Onuwa Ojekere",
    username: "Silvia",
    zeduName: "Silvia",
    background: "Customer Support",
    email: "silviaooje@gmail.com",
    linkedin: "silviaoje",
    avatarGradient: "from-tertiary-500 to-secondary-400",
  },
  {
    id: "kestrel-13",
    name: "Aaron Wisdom",
    username: "Barondev",
    zeduName: "Barondev",
    background: "Software Engineer",
    email: "aaronwisdom43@gmail.com",
    linkedin: "aaron-wisdom",
    avatarGradient: "from-primary-400 to-blue-500",
  },
  {
    id: "kestrel-14",
    name: "Afolabi Abdulbasit Opeyemi",
    username: "Aphoe",
    zeduName: "Aphoe",
    background: "Web Developer & WordPress Developer",
    email: "abdulbasitafolabi7@gmail.com",
    linkedin: "afolabi-abdulbasit-604784275",
    avatarGradient: "from-primary-500 to-blue-400",
  },
  {
    id: "kestrel-15",
    name: "Hamzat Ridwan Oladipupo",
    username: "ridwan hamzat",
    zeduName: "ridwan hamzat",
    background: "Frontend Developer",
    email: "ridwanhamzat99@gmail.com",
    avatarGradient: "from-secondary-500 to-primary-400",
  },
  {
    id: "kestrel-16",
    name: "Divyanshi Pathak",
    username: "divyanshi pathak",
    zeduName: "divyanshi pathak",
    background: "Full-Stack Developer",
    email: "divyanshipathakqc@mpgi.edu.in",
    linkedin: "divyanshi-pathak-profile",
    avatarGradient: "from-alert-400 to-primary-500",
  },
  {
    id: "kestrel-17",
    name: "Freda Onyinyechi Agha",
    username: "aghafreda",
    zeduName: "aghafreda",
    background: "Product Management",
    email: "aghafreda@gmail.com",
    linkedin: "freda-agha-0ab54b230",
    avatarGradient: "from-tertiary-500 to-primary-400",
  },
  {
    id: "kestrel-18",
    name: "Liberty Joseph",
    username: "Mrwayne",
    zeduName: "Mrwayne",
    background: "Software Engineer",
    email: "Wayneliberty33@gmail.com",
    linkedin: "liberty-wayne-787081440",
    avatarGradient: "from-blue-500 to-secondary-400",
  },
  {
    id: "kestrel-19",
    name: "Michael Samuel",
    username: "samstar",
    zeduName: "samstar",
    background: "Backend Development",
    email: "michaelsamstar@gmail.com",
    linkedin: "samuel-michael-0a2a47383",
    avatarGradient: "from-primary-500 to-alert-400",
  },
  {
    id: "kestrel-092",
    name: "Fabian Chibuike Muoghalu",
    username: "Fabbenco",
    zeduName: "Fabbenco",
    background: "Backend / Full-Stack / AI Engineer",
    email: "fabbenco97@gmail.com",
    linkedin: "fabian-muoghalu-37aa7a1a9",
    avatarGradient: "from-secondary-500 to-tertiary-400",
  },
  {
    id: "kestrel-022",
    name: "Onaopemipo Oyelami",
    username: "Nopylyn",
    zeduName: "Nopylyn",
    background: "Product Management",
    email: "oyelamionaopemipo@gmail.com",
    avatarGradient: "from-primary-500 to-blue-400",
  },
  {
    id: "kestrel-20",
    name: "Adewumi Oluwasanmi",
    username: "AdewumiOluwasanmi",
    zeduName: "AdewumiOluwasanmi",
    background: "Backend Developer",
    email: "oluwasanmiadewumi7@gmail.com",
    linkedin: "oluwasanmi-adewumi-b53799268",
    avatarGradient: "from-secondary-500 to-tertiary-400",
  },
  {
    id: "kestrel-093",
    name: "Maryjane Okafor (Emjay)",
    username: "Emjay",
    zeduName: "maryjane_okafor",
    background: "Software Engineer",
    email: "maryukjane@gmail.com",
    avatarGradient: "from-blue-400 to-tertiary-500",
  },
  {
    id: "kestrel-202",
    name: "Mercy Gatwiri",
    username: "M-gatwiri",
    zeduName: "M-gatwiri",
    background: "Software Developer",
    email: "mgatwiri806@gmail.com",
    linkedin: "mercy-gatwiri-17454b228",
    avatarGradient: "from-primary-500 to-secondary-400",
  },
  {
    id: "kestrel-021",
    name: "DIVINE CHUKWUDI",
    username: "D.C.",
    zeduName: "D.C.",
    background: "Backend / Full-Stack / AI Developer",
    email: "d-grid@outlook.com",
    linkedin: "DIVINE CHUKWUDI",
    avatarGradient: "from-secondary-500 to-tertiary-400",
  },
];
