export type Contributor = {
  name: string;
  username: string;
};

export const zeduOspreyContributors: Contributor[] = [
  { name: "Abdulrahman Abdulwasiu", username: "AbuDev" },
  { name: "Abiona Boluwatife", username: "DesignsbyB" },
  { name: "Adaeze Ifeanyi", username: "Adaeze" },
  { name: "Adaeze Ikemefuna", username: "Hamsa" },
  { name: "Adesua Benita", username: "Susu" },
  { name: "Adewale Abdul-Lateef Odukoya", username: "Adewale.py" },
  { name: "Ajayi Daniel", username: "Dahak" },
  { name: "Aliu Kamalideen Usman", username: "uthman tech" },
  { name: "Avi", username: "Avi" },
  { name: "Bahir Momodu", username: "BAGHIRA" },
  { name: "Ctrlf-codex", username: "CtrlF" },
  { name: "Daniel Iderima 😎", username: "daniel_iderima" },
  { name: "Delbiewonder", username: "Senorita" },
  { name: "Eddy Ukpong", username: "Eddy" },
  { name: "Ejiro Francess Ejoh", username: "ejiro frances" },
  { name: "Ekekwe Chinonso Charles", username: "xharlessnow" },
  { name: "Elijah Victor", username: "Stark" },
  { name: "Emmanuel Ekwere", username: "Emmy Anie" },
  { name: "Faizal Temitope", username: "Faizal" },
  { name: "Favour Alemika", username: "Code Flexie" },
  { name: "Fuhad", username: "phurhard" },
  { name: "Garuba Abdulazeez", username: "devAzeejim()" },
  { name: "Ilesanmi-Ojo Temitope", username: "Temmyactive" },
  { name: "Irfat", username: "Irfat" },
  { name: "Irfat-code", username: "Irfat-code" },
  { name: "Isaac Gideon", username: "vxrcel" },
  { name: "Iyola Oyabiyi", username: "iyoolaoyabiyi" },
  { name: "Joshua O. Adebisi", username: "Forty Eight" },
  { name: "Leo", username: "Beelzebub" },
  { name: "Marizu Esther", username: "High Babe" },
  { name: "Maureen Obiekwe", username: "Human AI" },
  { name: "Obinna Chidi", username: "Lisan al Gaib" },
  { name: "Olukemi Odedeyi", username: "Sh3HasN0Nam3" },
  { name: "Oluwakorede Adegbehingbe", username: "Korede" },
  { name: "Oluwanifemi Adeyemi", username: "Rondo" },
  { name: "Oshin Samuel", username: "bobbysam" },
  { name: "Oyindamola Adewole", username: "Oyindamola Adewole" },
  { name: "Pauline Banye", username: "Lynn Bee" },
  { name: "PcNerd", username: "new_here" },
  { name: "Pulse Tech Analytics", username: "Pulse Analytics" },
  { name: "Samson Oluwaseun Bakare", username: "Samjean" },
  { name: "Sarah Adetomiwa", username: "Big Miwa" },
  { name: "Sodiq Aliu Kamalideen", username: "sodiqbinaliu" },
  { name: "Udoh, Ubokabasi Odudu", username: "Basi" },
  { name: "Yusuf Bashir Nayaya", username: "Ybee" },
  { name: "ZuliyatG", username: "Pom Pom" },
  { name: "Gift Osanebi", username: "osanebigift" },
];
