import type { Contributor } from "~/app/(homepage)/contributors/zedu-osprey/_lib/contributors";

export const zeduQuetzalContributors: Contributor[] = [
  { name: "Omolara", username: "melancholia" },
  { name: "Tobiloba Similoluwa", username: "Tasiwewe" },
  { name: "Taiwo Omotola", username: "conversely" },
  { name: "Isaac Josiah", username: "isaac josiah" },
  { name: "Bigtiffs", username: "Bigtiffs" },
  { name: "Uchechukwu Samuel", username: "usamuelchukwu" },
  { name: "Abel promise", username: "Abel promise" },
  { name: "Isioma Peter", username: "isioma_peter" },
  { name: "Deborah Udochukwu Obiorah", username: "Deborah Obiorah" },
  { name: "GIFT OLUKOJU", username: "gift_olukoju" },
  { name: "Denise Moemeke", username: "denise_davida" },
  { name: "Enemuo Vivian Chiagozie", username: "vivian enemuo" },
  { name: "Opeyemi Oyeyipo", username: "YemiOye" },
  { name: "Basi", username: "Basi" },
  { name: "Olanrewaju john", username: "johnlanre573" },
  { name: "Increase Akinwole", username: "increaseakinwole" },
  { name: "Douye Frank", username: "douye frank" },
  { name: "Canon", username: "Canon" },
  { name: "Oluwayoyinsola Cecil", username: "Cyrus" },
  { name: "Hauwa Ismail Ahmad", username: "Hauwa Ismail" },
  { name: "Okorie winner", username: "Okorie winner" },
  { name: "Paul Folorunsho Folorunsho", username: "Paul Folorunsho" },
  { name: "Ibiyemi", username: "Ibiyemi" },
  { name: "Nsisong Uko", username: "Nsisong Uko" },
  { name: "Ajala Oladunsi Esther", username: "Oladunsi ajala" },
  { name: "Ken Osian", username: "kenosian" },
  { name: "benita idachaba", username: "benita idachaba" },
  { name: "Oduola Fawaz", username: "Fawizzy" },
  { name: "Fakile Razaq", username: "ArrJay" },
  { name: "Zainab Enifeni", username: "Eza" },
  { name: "Temilade Ajiboye", username: "Temilade Ajiboye" },
  { name: "Ezra Samuel", username: "Ezraone" },
  { name: "Ochife Ifunaya", username: "Ochife Ifunanya" },
  { name: "MOSHOOD BASHIR MAYOWA", username: "Moshood bashir mayowa" },
  { name: "OLUWASOLA MICHAEL ADEREMI", username: "CHRISTADEM" },
  { name: "Tanimomo Yetunde", username: "Yetunde" },
  { name: "Grace Muthoki", username: "grace muthoki" },
  { name: "Jamiu Aliyu Adekunle", username: "Cisse" },
  { name: "Muhibi Mukhtar Adekunle", username: "mukhtar_adekunle_01" },
  { name: "Confidence Osaze Aigbedion", username: "Confidence Aigbedion" },
  { name: "Haruna Mukhtar Ozoveh", username: "mukhtar_haruna" },
  { name: "Abdulkareem Rukayat", username: "Adebimpe" },
  { name: "Joshua Emenike", username: "Joshua ndu" },
  { name: "Abayomi Abubakar Ademola", username: "Abayomi Abubakar" },
  { name: "Mirabel Ade", username: "Mirabel Ade" },
  { name: "Olorunfemi Raimot Opeyemi", username: "Raheemah" },
  { name: "Adeleye Arafat", username: "Arafat" },
  { name: "Abdurrahman Adam", username: "Boileen" },
  { name: "Jennifer Oseghale", username: "jennifer_oseghale" },
  { name: "Odunsi Olatunde", username: "Triple O" },
  { name: "Obimba Samuel", username: "obimz" },
  { name: "Joshua Emmanuel", username: "Joshua" },
  { name: "JOSIAH ACHESE", username: "JOSIAH" },
  { name: "Annie", username: "anniedevkiller" },
  { name: "Michael Ndianaobong Churchill", username: "D-Gen" },
  { name: "Bayode Manuel", username: "Senior Man" },
];
