export type Contributor = {
  name: string;
  username: string;
};

export const zeduDrongoContributors: Contributor[] = [
  { name: "Emmanuel Okonkwo", username: "Rabbi_Manuel" },
  { name: "Fashina Isaac", username: "Highzik" },
  { name: "Muhammad Mustapha Bello", username: "Muhammad Mustapha Bello" },
  { name: "Atilola Emmanuel", username: "Emmanuel Atilola" },
  { name: "Bakare Muftiat", username: "dev_elixir" },
  { name: "John Divine", username: "dicint" },
  { name: "Yaasir Titilope Adigun", username: "Yaasir" },
  { name: "Victor Adeshile", username: "victor_adeshile" },
  { name: "Ikah Collins ifebuche", username: "Idan Codes" },
  { name: "Rukayyah Ibrahim", username: "cocoon" },
  { name: "Amartey Rukayya Yusuf", username: "rukayya yusuf amartey" },
  { name: "Eda Cynthia Itsekirimi", username: "Cynthy" },
  { name: "Carlson Chibueze Oranu", username: "carlson" },
  { name: "Uyanwanne Emmanuel Chukwudaru", username: "emmyanzo" },
  { name: "Jonathan James Omini", username: "James Jonathan" },
  { name: "Collins", username: "Collins Odogwu" },
  { name: "Moses Ogunade", username: "Cosmic Atomic" },
  { name: "Adefemiwa Damilare Quadry", username: "Dreymi" },
  { name: "Nwabueze Chukwu Sunday", username: "Maxdesigns01" },
  {
    name: "Lasisi Oluwatimilehin Joshua",
    username: "Lasisi Oluwatimilehin Joshua",
  },
  { name: "Alfred Ogu", username: "alfred." },
  { name: "Ahmad Magaji Abdullahi", username: "teejey _ahmad" },
  { name: "Salvation Azuh", username: "Chavon" },
  {
    name: "Winjobi Oluwafunmilola Oyindamola",
    username: "Winjobifunmi",
  },
  { name: "Mesode Kelly Akwe", username: "mesode_akwe" },
  { name: "Ifeanyichukwu Gideon Eloka", username: "gideoneloka" },
  { name: "Odofin Moronke", username: "Sparklynjewel" },
  { name: "Isaac Ogugua Eberechukwu", username: "OBA" },
  { name: "Chaydee Hilary", username: "Lahrry" },
  { name: "Umeoke Ozioma", username: "Ozioma Umeoke" },
  { name: "Azeezat Morenikeji Olanihun", username: "azeezatolanihun" },
  { name: "MARY IRAWOOLA OLADIMEJI", username: "Mirawoola" },
  { name: "Bolarinwa Oyerinde", username: "bolaoye" },
  { name: "UTIBE BASSEY", username: "ragnar" },
  { name: "Abass Adejoke salma", username: "Adejoke Salma" },
  { name: "Paul Dirisu", username: "padolabs" },
  { name: "Obiekwe Rita", username: "Rixbyte" },
  { name: "Obasola Eniola", username: "Eniola Obasola" },
  { name: "Doris King-Paul", username: "Mochasset" },
  { name: "Victor Oluwayemi", username: "Victor.OL" },
  { name: "Daniel Ugot", username: "Daniel Ugot" },
  { name: "Seife Meklit", username: "meklitseife86" },
  { name: "Sheriff Afolabi", username: "sheriff-afolabi" },
  { name: "Abuchi Nwajagu Collins", username: "Collinsthegreat" },
  { name: "Nzubechukwu Diara", username: "Diara" },
  { name: "Pamela Patrick", username: "Pam" },
  { name: "Charles Adesoba", username: "Carl-ade" },
  { name: "Ibrahim Nurudeen Shehu", username: "Techienuru" },
  { name: "Fatimah Olaitan", username: "thetitilola" },
  { name: "Maryanne Omage", username: "mimi" },
  { name: "Bakare Oluwatomisin", username: "oluwatomisin_bakare" },
  { name: "Oladapo Ajiboye", username: "Oladapo.Jacob" },
  { name: "Ubong David Umoette", username: "UbongUmoette" },
  { name: "John Ureke", username: "john ureke" },
  { name: "Bamidele Salman", username: "Bamidele Salman" },
  { name: "Richard Christopher Oduh", username: "Richard oduh" },
  { name: "Adebayo Mercy", username: "adebayo mercy" },
  { name: "Oluwafemi Moses Oladipo", username: "Oluwafemi Oladipo" },
  { name: "Adewale Abdulmajeed Ajibola", username: "Jeedy" },
  { name: "John Nnamdi", username: "Unkle jhonie" },
  { name: "Daniel Olaleye", username: "Vida" },
  { name: "Sofiyah Owolabi", username: "Sophie" },
  { name: "Akinsoyinu Vincent", username: "vince.dev" },
  { name: "Arafah Muhyideen", username: "Dhinar" },
  { name: "Anuonye Chidera Victor", username: "Victor Courage" },
  { name: "Onyedikachi Oluchi", username: "Jemi" },
  { name: "Muhammad Abubakar Sadiq", username: "Sadiq" },
];
